name: test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  tflite: ^1.1.2
  image_picker: ^0.8.3+2

  # For app logo 
  flutter_launcher_icons: ^0.9.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo0.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
